### ISSUE TITLE
Make interactive plot

### ISSUE THREAD

**Issue by JaniceShu** [Helseatlas/helseatlas#140]
use Plotly?
pop up box when roll over a column
annotation (data sources) need to reflect the correct language
legend (breaks) should flip around so that it correspond to the plot better

**Comment by JaniceShu** [comment]
@arnfinn I noticed the ggplot2::guide_colorsteps in plot_variation.r.  Was it you that added it?  Just wondering what are the thoughts behind that.  I'm trying to use plotly to make the ggplot2 output interactive and it is now showing both the colorsteps and the legend as it was before.  The colorsteps has the more correct display corresponding to the graph (darker color on top) while the other legend allow it to be interactive (select / de-select groups).  
![plotly](https://user-images.githubusercontent.com/33416297/82214567-56094600-9916-11ea-9fd7-41160b4f00ab.png)
It is possible that the output from ggplot2 was the regular legend with the correct display, and plotly decided to show both, which is kinda silly.

**Comment by arnfinn** [comment]
It was added here by @Tovjoh: 2609c387
Not sure we need to be able to select groups, but I might be wrong.
